### ISSUE TITLE
Download link not found

### ISSUE THREAD

**Issue by janfer95** [cmudrc/MegaFlow2D#6]
Hi, thank you for your great work! 

I tried to download the dataset, however, when downloading it the code throws the error `HTTP Error 404: Not found` and indeed, manually using the download link leads to the same error in a browser. 

On huggingface I can see that the individual data files exist (data.zip.001, etc.), but no common one. 

Would it be possible to fix the link or to upload a bundled version? 

Thanks already!

**Comment by WenzhuoXu** [comment]
Sorry for the confusion! I’ve recently updated the files but haven’t had time to update the package accordingly. I’m a bit busy these days and perhaps wouldn’t have a chance to update the package until mid September, what you can do right now is to manually unzip the files and put them in the ‘/path_to_root/raw’ folder so that when you initialize the dataset package it would automatically skip the download process. Sorry again for the inconvenience!

**Comment by janfer95** [comment]
No worries! Thank you for your quick reply, I'll try it out right away! 

Edit: Turns out that the pip package is one version lower than the one on github. 
Using `pip install git+https://github.com/cmudrc/MegaFlow2D` solved the problem for me.
